services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ineed
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: ineed-ai
    depends_on:
      - db
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      # redundante mas explícito
      DATABASE_URL: ${DATABASE_URL}
      PORT: "3000"
      NODE_ENV: production
    restart: unless-stopped

volumes:
  pgdata: