import type { Category, Testimonial, User } from './types';

export const INEED_LOGO_SVG_URI = "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 576 512'%3E%3Cpath fill='%2300b4db' d='M480 96c0-35.3-28.7-64-64-64s-64 28.7-64 64s28.7 64 64 64s64-28.7 64-64zM320 288c0-12.9-6.3-24.5-16.8-31.9l-1.8-1.3c-8.9-6.4-17.6-13.3-26-20.6c-21.3-18.6-45.4-38.3-70.3-59.5C189.9 161.2 169 152.1 146.1 152c-2.3 0-4.6 .1-6.9 .2c-38.8 2.2-68.5 34.6-68.5 73.8V352c0 17.7 14.3 32 32 32s32-14.3 32-32V240.2c0-4.2 3.4-7.6 7.6-7.6c1.1 0 2.2 .2 3.2 .6c16.3 5.3 36.3 17.2 56.4 31.9c25.4 18.5 52.3 39.8 79.2 60.3c2.5 1.9 5.2 3.7 7.9 5.5c1.4 .9 2.7 1.8 4.1 2.7c16.3 11.2 36.3 17.2 56.4 17.2c61.9 0 112-50.1 112-112s-50.1-112-112-112zm-8.2 128c-11.8 0-23.4-2.2-34.3-6.4c-4.9-1.9-8.2-6.9-6.4-11.8c1.9-4.9 6.9-8.2 11.8-6.4c8.4 3.2 17.3 4.9 26.2 4.9c26.5 0 48-21.5 48-48s-21.5-48-48-48s-48 21.5-48 48c0 1.9 .1 3.7 .4 5.5c2.1 13.7-4.1 27.5-16.3 34.9c-15.1 9.2-34.3 6.9-47.3-5.9c-2-1.9-4-3.9-5.9-5.9c-25.9-20.9-53.5-42.7-79.6-61.7c-17.4-12.6-35.3-23.2-52.2-30.9c-2.8-1.2-5.9-1.8-8.9-1.8c-17.7 0-32-14.3-32-32s14.3-32 32-32c2.8 0 5.6 .3 8.3 .9c32.4 6.8 57.8 20.3 81.3 37.8c25.2 18.7 49.6 38.6 71.3 57.6c8.5 7.4 17.1 14.2 25.7 20.7l1.8 1.3c15.2 9.4 32.2 14.6 49.5 14.6c39.8 0 72 32.2 72 72s-32.2 72-72 72z'/%3E%3C/svg%3E";

export const CATEGORIES: Category[] = [
  // --- SERVIÇOS ---
  { id: 'cat-serv-1', name: 'Tecnologia', description: 'Assistência, aulas e reparos', icon: 'fas fa-laptop-code', color: 'bg-blue-500', type: 'service' },
  { id: 'cat-serv-2', name: 'Casa e Reparos', description: 'Limpeza, jardinagem e consertos', icon: 'fas fa-tools', color: 'bg-green-500', type: 'service' },
  { id: 'cat-serv-3', name: 'Roupas e Ajustes', description: 'Costura, customização e confecção', icon: 'fas fa-cut', color: 'bg-purple-500', type: 'service' },
  { id: 'cat-serv-4', name: 'Alimentos e Buffet', description: 'Aulas, marmitas e eventos', icon: 'fas fa-utensils', color: 'bg-orange-500', type: 'service' },
  { id: 'cat-serv-5', name: 'Saúde e Bem-estar', description: 'Cuidados, aulas e acompanhamento', icon: 'fas fa-heartbeat', color: 'bg-red-500', type: 'service' },
  { id: 'cat-serv-6', name: 'Pets (Serviços)', description: 'Cuidadores, passeadores e adestradores', icon: 'fas fa-paw', color: 'bg-yellow-500', type: 'service' },
  { id: 'cat-serv-7', name: 'Beleza e Cuidado', description: 'Cabeleireiros, estética e mais', icon: 'fas fa-spa', color: 'bg-pink-500', type: 'service' },
  { id: 'cat-serv-8', name: 'Esportes e Lazer', description: 'Aulas e personal trainers', icon: 'fas fa-dumbbell', color: 'bg-teal-500', type: 'service' },
  { id: 'cat-serv-9', name: 'Transporte e Logística', description: 'Caronas, fretes e mudanças', icon: 'fas fa-truck', color: 'bg-amber-600', type: 'service' },
  { id: 'cat-serv-10', name: 'Hospedagem', description: 'Quartos, casas ou apartamentos', icon: 'fas fa-bed', color: 'bg-cyan-500', type: 'service' },
  { id: 'cat-serv-11', name: 'Aulas & Workshops', description: 'Idiomas, música, reforço escolar', icon: 'fas fa-chalkboard-teacher', color: 'bg-indigo-500', type: 'service' },
  { id: 'cat-serv-12', name: 'Empregos & Vagas', description: 'Anuncie ou encontre oportunidades', icon: 'fas fa-briefcase', color: 'bg-slate-500', type: 'service' },
  { id: 'cat-serv-13', name: 'Consultoria & Negócios', description: 'Finanças, carreira e gestão', icon: 'fas fa-chart-pie', color: 'bg-zinc-700', type: 'service' },
  { id: 'cat-serv-14', name: 'Fotografia & Vídeo', description: 'Ensaios, eventos e filmagens', icon: 'fas fa-camera-retro', color: 'bg-rose-500', type: 'service' },
  { id: 'cat-serv-15', name: 'Jurídico & Contabilidade', description: 'Serviços profissionais', icon: 'fas fa-balance-scale', color: 'bg-gray-600', type: 'service' },
  { id: 'cat-serv-16', name: 'Ajuda Comunitária', description: 'Pedidos de ajuda. Gratuito.', icon: 'fas fa-hands-helping', color: 'bg-emerald-500', type: 'service' },
  { id: 'cat-serv-17', name: 'Denúncias', description: 'Alertas para a comunidade.', icon: 'fas fa-bullhorn', color: 'bg-red-700', type: 'service' },
  { id: 'cat-serv-18', name: 'Doações', description: 'Ajude quem precisa com itens.', icon: 'fas fa-hand-holding-heart', color: 'bg-fuchsia-500', type: 'service' },
  { id: 'cat-serv-19', name: 'Crianças', description: 'Babás, aulas particulares e mais', icon: 'fas fa-child', color: 'bg-sky-400', type: 'service' },

  // --- PRODUTOS ---
  { id: 'cat-prod-1', name: 'Artesanato', description: 'Produtos únicos feitos à mão', icon: 'fas fa-paint-brush', color: 'bg-amber-500', type: 'product' },
  { id: 'cat-prod-2', name: 'Eletrônicos', description: 'Celulares, notebooks e mais', icon: 'fas fa-laptop', color: 'bg-sky-500', type: 'product' },
  { id: 'cat-prod-3', name: 'Aluguéis', description: 'Alugue itens, de ferramentas a veículos', icon: 'fas fa-key', color: 'bg-lime-500', type: 'product' },
  { id: 'cat-prod-4', name: 'Imóveis', description: 'Compra, venda e aluguel', icon: 'fas fa-city', color: 'bg-orange-600', type: 'product' },
  { id: 'cat-prod-5', name: 'Comida (Produtos)', description: 'Ingredientes, refeições e mais', icon: 'fas fa-shopping-basket', color: 'bg-red-400', type: 'product' },
  { id: 'cat-prod-6', name: 'Festas e Eventos', description: 'Artigos para festas e decoração', icon: 'fas fa-birthday-cake', color: 'bg-pink-400', type: 'product' },
  { id: 'cat-prod-7', name: 'Auto Peças', description: 'Peças e acessórios para seu veículo', icon: 'fas fa-car-battery', color: 'bg-stone-500', type: 'product' },
  { id: 'cat-prod-8', name: 'Móveis e Eletro', description: 'Para sua casa', icon: 'fas fa-couch', color: 'bg-amber-700', type: 'product' },
  { id: 'cat-prod-9', name: 'Crianças', description: 'Brinquedos, roupas e artigos', icon: 'fas fa-baby-carriage', color: 'bg-teal-400', type: 'product' },
  { id: 'cat-prod-10', name: 'Pets (Produtos)', description: 'Ração, brinquedos e acessórios', icon: 'fas fa-dog', color: 'bg-yellow-400', type: 'product' },
  { id: 'cat-prod-11', name: 'Ferramentas', description: 'Venda ou aluguel de ferramentas', icon: 'fas fa-screwdriver', color: 'bg-gray-500', type: 'product' },
  { id: 'cat-prod-12', name: 'Livros e Hobbies', description: 'Troca, compra e venda', icon: 'fas fa-book-open', color: 'bg-green-600', type: 'product' },
  { id: 'cat-prod-13', name: 'Veículos', description: 'Carros, motos e barcos', icon: 'fas fa-car', color: 'bg-zinc-700', type: 'product' },
  { id: 'cat-prod-14', name: 'Ingressos & Vouchers', description: 'Para shows, eventos e mais', icon: 'fas fa-ticket-alt', color: 'bg-rose-400', type: 'product' },
  { id: 'cat-prod-15', name: 'Equipamentos Esportivos', description: 'Bicicletas, pesos, bolas', icon: 'fas fa-bicycle', color: 'bg-lime-600', type: 'product' },
  { id: 'cat-prod-16', name: 'Jardinagem & Plantas', description: 'Mudas, vasos e ferramentas', icon: 'fas fa-seedling', color: 'bg-emerald-600', type: 'product' },
  { id: 'cat-prod-17', name: 'Moda e Acessórios', description: 'Roupas, sapatos e bolsas', icon: 'fas fa-tshirt', color: 'bg-violet-600', type: 'product' },
  { id: 'cat-prod-18', name: 'Instrumentos Musicais', description: 'Violões, teclados, baterias', icon: 'fas fa-guitar', color: 'bg-cyan-600', type: 'product' },
];

export const TESTIMONIALS: Testimonial[] = [
    {
        id: 1,
        text: 'Encontrei um profissional incrível para consertar meu vazamento em menos de uma hora. O iNeed salvou meu dia!',
        authorName: 'Mariana Silva',
        authorRole: 'Usuária Verificada',
        avatar: 'https://i.pravatar.cc/150?img=1',
    },
    {
        id: 2,
        text: 'Como designer freelancer, o iNeed abriu um novo canal de clientes para mim. A plataforma é fácil de usar e muito eficiente.',
        authorRole: 'Fornecedor Premium',
        authorName: 'João Pereira',
        avatar: 'https://i.pravatar.cc/150?img=2',
    },
    {
        id: 3,
        text: 'Precisava de um bolo de aniversário de última hora e consegui uma confeiteira maravilhosa perto de casa. Recomendo!',
        authorRole: 'Usuária Verificada',
        authorName: 'Carla Souza',
        avatar: 'https://i.pravatar.cc/150?img=3',
    },
];

export const MOCK_USER: User = {
  id: 'user123',
  name: '',
  username: '',
  avatarUrl: '',
  bio: '',
  location: '',
  memberSince: '',
  isPremium: false,
  rating: { average: 0, count: 0 },
  verifications: { email: false, phone: false, document: false },
  serviceArea: { center: { lat: 0, lng: 0 }, radius: 0 },
  pricing: 0,
  workingHours: '',
  serviceCategories: [],
  portfolio: [],
  ordersAsClient: [],
  ordersAsProvider: [],
  reviewsAsClient: [],
  conversations: [],
  notifications: [],
  unreadMessagesCount: 0,
  unreadNotificationsCount: 0,
};

export const MOCK_PROVIDER: User = {
  id: 'provider456',
  name: 'Roberto Andrade',
  username: 'roberto_tech',
  avatarUrl: 'https://i.pravatar.cc/150?u=provider456',
  bio: 'Técnico em informática com mais de 10 anos de experiência em reparos de notebooks e desktops. Atendimento rápido e de confiança!',
  location: 'São Paulo, SP',
  memberSince: 'Março de 2022',
  isPremium: true,
  rating: { average: 4.9, count: 87 },
  verifications: { email: true, phone: true, document: true },
  serviceArea: { center: { lat: -23.55052, lng: -46.633308 }, radius: 10000 },
  pricing: 7,
  workingHours: "Seg-Sex, 9h-18h",
  serviceCategories: ['cat-serv-1', 'cat-prod-2'],
  portfolio: [
    'https://images.unsplash.com/photo-1588392382834-a891154bca4d?q=80&w=800',
    'https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?q=80&w=800',
  ],
  ordersAsClient: [],
  ordersAsProvider: [],
  reviewsAsClient: [],
  conversations: [],
  notifications: [],
  unreadMessagesCount: 0,
  unreadNotificationsCount: 0,
};